services:
  app:
    build:
      context: .
      target: dev
    container_name: upside
    env_file:
      - .env
    restart: unless-stopped
    environment:
      NODE_ENV: development
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3002:3000"
    command: bun run dev
